# MetalLB IPAddress Pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.49.150-192.168.49.160
---
# MetalLB L2 Advertisement Configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          args: ["redis-server", "--requirepass", "password"]
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: urlshortener-secret
                  key: REDIS_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
# URL Shortener ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: urlshortener-config
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  BASE_URL: "http://192.168.49.150"
---
# URL Shortener Secret
apiVersion: v1
kind: Secret
metadata:
  name: urlshortener-secret
type: Opaque
stringData:
  REDIS_PASSWORD: "password"
---
# URL Shortener Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener
spec:
  selector:
    matchLabels:
      app: urlshortener
  replicas: 3
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          image: urlshortener:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: urlshortener-config
            - secretRef:
                name: urlshortener-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
---
# URL Shortener Service with LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: urlshortener
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  type: LoadBalancer
  selector:
    app: urlshortener
  ports:
    - port: 80
      targetPort: 5000
